version: 2

jobs:
  build:
    docker:
    - image: ankyra/escape:latest

    steps:
    - checkout
    - setup_remote_docker
    - run: 
        name: Build Escape release
        command: escape release
